modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="magical_artifacts"
version="1.0.0"
displayName="magical_artifacts"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="ryzhenko.na, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.magical_artifacts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.magical_artifacts]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.magical_artifacts]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

